#!/bin/bash

if [ $1 == "--dev" ]; then 
    echo "Building WASM Index Code (Development)";
    emcc --js-library "index.js" mdb.o midl.o index.cpp -l liblmdb -L . -s ALLOW_MEMORY_GROWTH=1 -s FORCE_FILESYSTEM=1 -s NODERAWFS=1 -s WASM=1 -std=c++11 -s SINGLE_FILE=1 --bind -o db.js;
else
    echo "Building WASM Index Code";
    emcc --js-library "index.js" index.cpp -l sqlite  -L . -s ERROR_ON_UNDEFINED_SYMBOLS=0 -s ALLOW_MEMORY_GROWTH=1 -s FORCE_FILESYSTEM=1 -s NODERAWFS=1 -s WASM=1 -std=c++11 -s SINGLE_FILE=1 -Os --bind -o ../src/db.js;
fi

# emcc -Os sqlite3.c -s LINKABLE=1 -s EXPORT_ALL=1 -DSQLITE_THREADSAFE=0 -DSQLITE_DEFAULT_MEMSTATUS=0 -DSQLITE_OMIT_DECLTYPE -DSQLITE_MAX_EXPR_DEPTH=0 -DSQLITE_OMIT_SHARED_CACHE -DSQLITE_OMIT_PROGRESS_CALLBACK -DSQLITE_OMIT_DEPRECATED -DSQLITE_OMIT_ALTERTABLE -DSQLITE_OMIT_ANALYZE -DSQLITE_OMIT_ATTACH -DSQLITE_OMIT_AUTHORIZATION -DSQLITE_OMIT_AUTOINCREMENT -DSQLITE_OMIT_BETWEEN_OPTIMIZATION -DSQLITE_OMIT_BLOB_LITERAL -DSQLITE_OMIT_BTREECOUNT -DSQLITE_OMIT_CAST -DSQLITE_OMIT_CHECK -DSQLITE_OMIT_COMPOUND_SELECT -DSQLITE_OMIT_DATETIME_FUNCS -DSQLITE_OMIT_EXPLAIN -DSQLITE_OMIT_FLAG_PRAGMAS -DSQLITE_OMIT_FOREIGN_KEY -DSQLITE_OMIT_GET_TABLE -DSQLITE_OMIT_LIKE_OPTIMIZATION -DSQLITE_OMIT_LOAD_EXTENSION -DSQLITE_OMIT_LOCALTIME -DSQLITE_OMIT_OR_OPTIMIZATION -DSQLITE_OMIT_REINDEX -DSQLITE_OMIT_SUBQUERY -DSQLITE_OMIT_VIEW -DSQLITE_OMIT_VIRTUALTABLE -o sqlite.so